### ISSUE TITLE
Unify component test and story/docz

### ISSUE THREAD

**Issue by guilhermedecampo** [Astrocoders/astroman#4]
`astro-cli gen jscomponent Header`

generates: Header.js Header.test.js Header.mdx

**Comment by eliabejr** [comment]
put it on 
https://github.com/Astrocoders/astro-cli/pull/3/commits/20be9efed517afbd86b18d77a2f8c6ba8bfe7386

now, you can specify language, then, astro-cli generate the right components
`astro-cli gen component js Header`

you also can run each command separately
